# Generated by Django 5.0.6 on 2024-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='red_threshold',
            field=models.IntegerField(blank=True, default=128, verbose_name='Пороговое значение для выборки пикселей'),
        ),
    ]
